### ISSUE TITLE
Error with new entries: NoneType no split attribute

### ISSUE THREAD

**Issue by Tom866** [39aldo39/Radicale-DecSync#8]
Hi, I love the idea of DecSync.
I am trying to make a simple setup working. New entries on my phone are properly synced to the thunderbird client (V78.6.0 32bit) via syncthing and radicale (V3.0.6) (at the moment running in an Anaconda prompt since I was not able to call pip and install radicale via normal cmd, radicale_storage_decsync plugin version is 1.2.0). When I delete contacts on my desktop thunderbird client, these changes propagate to my phone as expected. **However, when I make new entries such as contacts or calendar events from the desktop thunderbird client they do not propagate to my phone, the cmd window throws the following error:**
```
[2021-01-12 13:06:14 +0100] [16224/Thread-21] [ERROR] An exception occurred during PUT request on '/randomusername/contacts-random_string_of_characters/random_string_of_characters.vcf': 'NoneType' object has no attribute 'split'
```
with `--debug` on, the additional information is given:
```
Traceback (most recent call last):
  File "c:\users\my_windows_user_name\anaconda3\lib\site-packages\radicale\app\__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "c:\users\my_windows_user_name\anaconda3\lib\site-packages\radicale\app\__init__.py", line 276, in _handle_request
    status, headers, answer = function(
  File "c:\users\my_windows_user_name\anaconda3\lib\site-packages\radicale\app\put.py", line 210, in do_PUT
    etag = parent_item.upload(href, prepared_item).etag
  File "c:\users\my_windows_user_name\anaconda3\lib\site-packages\radicale_storage_decsync\__init__.py", line 99, in upload
    supported_components = self.get_meta("C:supported-calendar-component-set").split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```

I am not sure if this is a bug or it has to do with the settings of any of the software components. Please let me know if and how I can provide you with more information to see if we can resolve this issue and thereby hopefully help other people too.

Edit, maybe I should post this issue at the radical app: https://github.com/Kozea/Radicale/issues/748
I will try to see if this issue is also present without the radicale_storage_decsync plugin and post it in their thread. Will update when I do so!
Edit2: I did not get the same problem with the standard storage plugin. My minimum recreation for the example is:
Create the file C:\Users\my_windows_user_name\.config\radicale\test_conf:
```
[storage]
type = radicale_storage_decsync
filesystem_folder = C:\Users\my_windows_user_name\radicale\collections_test3
decsync_dir = C:\Users\my_windows_user_name\radicale\DecSync_test3
```
with both folder initially empty. Run `radicale --config=C:\Users\my_windows_user_name\.config\radicale\test_conf`. Login to the localhost webpage with username `a` and password `a`. Create a new contact list and copy the link. In thunderbird cardbook (extension), add a new contact list, select remote location, paste the contact addressbook URL and fill in the username and password with a. Now watch the cmd window and add a new contact in the newly created CardDAV addressbook.

Since the problem does not appear with:
```
[storage]
type = multifilesystem
filesystem_folder = C:\Users\my_windows_user_name\radicale\collections_test3
```
I am not sure if the problem is due to a bug in the DecSync-radicale plugin or if it has to do with a bug in the radicale package since multiple people have reported problems with the 'split' operation being performed on a 'NoneType'.

**Comment by 39aldo39** [comment]
Thanks for the report! I was able to reproduce the issue. It should be fixed in the next release.

**Comment by RilicTheFox** [comment]
> Thanks for the report! I was able to reproduce the issue. It should be fixed in the next release.

I've replaced the ___init___.py and tried using the new code mentioned in that commit, but the problem still seems to persist. Or is that simply one part of the fix?

**Comment by Tom866** [comment]
Hi, I also replaced the python code of init.py where the python library is installed. For me contacts are working, I can create and edit on Thunderbird on my PC and on my Android. I am an amateur, but when creating/editing/deleting contacts, I do not see any problems flashing by in the CMD when running Radicale with the `--debug` verbosity.

I managed to switch from Anaconda to Python3.9 as an interpreter.

I wanted to wait for 39aldo39 to officially release a new version before commenting further, but since you are also still stuck I can share the problems I still encounter. I cannot create calendar events on Thunderbird. When I create a new event the CMD says:
```
[2021-02-xx xx:xx:xx +xx00] [3264/Thread-33] [ERROR] An exception occurred during PUT request on '/xxxUser/calendars-RANDOM-STRING/OTHER-RANDOM-STRING.ics': 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\radicale\app\__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "C:\Python39\lib\site-packages\radicale\app\__init__.py", line 276, in _handle_request
    status, headers, answer = function(
  File "C:\Python39\lib\site-packages\radicale\app\put.py", line 210, in do_PUT
    etag = parent_item.upload(href, prepared_item).etag
  File "C:\Python39\lib\site-packages\radicale_storage_decsync\__init__.py", line 101, in upload
    supported_components = self.get_meta("C:supported-calendar-component-set").split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```

A few seconds later a lot of webserver html/json like code spits out and then I saw:
```
[2021-02-xx xx:xx:xx +xx00] [3264/Thread-40] [INFO] REPORT response status for '/xxxUser/calendars-RANDOMSTRING/' with depth '1' in 0.020 seconds: 207 Multi-Status
```

Then in Thunderbird a pop-up message says:
```
Error code: MODIFICATION_FAILED

Status Code: 2147746065, The request cannot be processed.

Server Replied with 500
If you're seeing this message after snoozing or dismissing a reminder and this is for a calendar you do not want to add or edit events for, you can mark this calendar as read-only to avoid such experience in future. To do so, get to the calendar properties by right-clicking on this calendar in the list in the calendar or task view.
```

@RilicTheFox Are both Contacts and Calendar events not working? What CMD messages do you see that look interesting when you run radical with the `--debug` option?

I am currently happy that the contacts are working and hope that in the future I can also create calendar events on my laptop :)

**Comment by renyuneyun** [comment]
@Tom866 I'm having a very similar debug message as you posted, though in my case it's for contacts -- calendars works correctly.
I also posted the request content, with a random person information ("name AA, telephone number 123123123").

```
[2021-03-26 11:34:05 +0000] [317510/Thread-62] [DEBUG] Sanitized path: '/xxxUser/contact-RANDOM-STRING/OTHER-RANDOM-STRING.vcf'
[2021-03-26 11:34:05 +0000] [317510/Thread-62] [DEBUG] Request content:
BEGIN:VCARD
FN:AA
TEL;TYPE=VOICE:123123123
UID:5934417f-40cd-48d0-9949-0d62946fe8a1
VERSION:3.0
N: ;;;;
END:VCARD
[2021-03-26 11:34:05 +0000] [317510/Thread-62] [ERROR] An exception occurred during PUT request on '/xxxUser/contact-RANDOM-STRING/OTHER-RANDOM-STRING.vcf': 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/radicale/app/__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/lib/python3.9/site-packages/radicale/app/__init__.py", line 276, in _handle_request
    status, headers, answer = function(
  File "/usr/lib/python3.9/site-packages/radicale/app/put.py", line 210, in do_PUT
    etag = parent_item.upload(href, prepared_item).etag
  File "/usr/lib/python3.9/site-packages/radicale_storage_decsync/__init__.py", line 99, in upload
    supported_components = self.get_meta("C:supported-calendar-component-set").split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```

It looks as if thunderbird / lightening doesn't supply the `C:supported-calendar-component-set` information, but DecSync is assuming it must exist. The name suggests it's for **calendar**, but I'm adding a **contact**/**addressbook** entry.

@39aldo39 Could that be due to a mis-implementation?

**Comment by therealjeybe** [comment]
Same error for me, doesn't seem to be fixed? Or is this Radicale and not DecSync related?

**Comment by 39aldo39** [comment]
Sorry for the delay. I just released the new version, which should fix the issue.

**Comment by Tom866** [comment]
@39aldo39 With the new version my issue does still persist. When creating a calendar event on my Android mobile it works and sync to my Thunderbird on my desktop. When creating a calendar event on Thunderbird it throws an error. Maybe with the content of the request you can find the error easier. 

```
[2021-04-07 22:27:31 +0200] [8064/Thread-25] [DEBUG] Request content:
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20210407T202720Z
LAST-MODIFIED:20210407T202731Z
DTSTAMP:20210407T202731Z
UID:xx-xx-x-xxx-xxx
SUMMARY:Test desktop study
DTSTART;TZID=Europe/Berlin:20210410T230000
DTEND;TZID=Europe/Berlin:20210411T000000
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

[2021-04-07 22:27:31 +0200] [8064/Thread-25] [ERROR] An exception occurred during PUT request on '/xxxUser/calendars-xxxxx-xxx-xxx-xx-xxx/xx-xx-x-xxx-xxx.ics': 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\radicale\app\__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "C:\Python39\lib\site-packages\radicale\app\__init__.py", line 276, in _handle_request
    status, headers, answer = function(
  File "C:\Python39\lib\site-packages\radicale\app\put.py", line 210, in do_PUT
    etag = parent_item.upload(href, prepared_item).etag
  File "C:\Python39\lib\site-packages\radicale_storage_decsync\__init__.py", line 101, in upload
    supported_components = self.get_meta("C:supported-calendar-component-set").split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```

I think there are still some flows where the `C:supported-calendar-component-set` is not getting defined. If I can find some time I can start looking at how to print stuff in the debug cmd window and try to trace back what the self.get_meta exactly contains and why the `C:supported-calendar-component-set` is not getting defined in my workflow.

**Comment by RilicTheFox** [comment]
Same issue as above when using Kontact Korganizer. Contacts, however, work fine for me, and I can sync them two-ways.
Running Artix Linux:
```
[2021-04-08 13:55:26 +0100] [2707/Thread-56] [ERROR] An exception occurred during PUT request on '/rilic/calendars-a9884084-7aa8-f9dd-1f31-79d19f6a93a8/1617886526.R313.ics': 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/radicale/app/__init__.py", line 105, in __call__
    status, headers, answers = self._handle_request(environ)
  File "/usr/lib/python3.9/site-packages/radicale/app/__init__.py", line 276, in _handle_request
    status, headers, answer = function(
  File "/usr/lib/python3.9/site-packages/radicale/app/put.py", line 210, in do_PUT
    etag = parent_item.upload(href, prepared_item).etag
  File "/usr/lib/python3.9/site-packages/radicale_storage_decsync/__init__.py", line 101, in upload
    supported_components = self.get_meta("C:supported-calendar-component-set").split(",")
AttributeError: 'NoneType' object has no attribute 'split'
```

@Tom866 Sorry for not responding originally a couple months back, I didn't realise I was tagged! I think it used to be both contacts and calendar, but now contacts are working as intended - it's just calendars that don't work.

**Comment by therealjeybe** [comment]
Issue persists for me, too. What I did:

`pip3 install --upgrade radicale_storage_decsync` and restarted Radicale with `systemctl --user restart radicale`.

My systemd file (`~/.config/systemd/user/radicale.service`) should be fine, I think, it simply starts Radicale:
```
[Unit]
Description=Radicale

[Service]
ExecStart=/usr/bin/env python3 -m radicale --config "~/.config/radicale/config"
Restart=on-failure

[Install]
WantedBy=default.target
```

The Radicale config (`~/.config/radicale/config`) looks as follows, should be fine, too, I think:
```
[storage]
type = radicale_storage_decsync
filesystem_folder = ~/.var/lib/radicale/collections
decsync_dir = ~/Sync/DecSync
```

Both decsync_dir and filesystem_folder do exist.


Exact error is: 
```
[2021-04-10 14:20:11 +0200] [18710/Thread-9] [ERROR] An exception occurred during PUT request on '/user/calendars-089c61f2-6c4b-0b04-f4bd-88b4428c449c/5830b900-553b-4663-83a5-883605348c64.ics': 'NoneType' object has no attribute 'split'
```

**Comment by 39aldo39** [comment]
I see, there was another bug that prevented `C:supported-calendar-component-set` from being set. This is now fixed and old collections will also work again.

**Comment by RilicTheFox** [comment]
It looks like it's fixed for me! Thanks a bunch!

**Comment by Tom866** [comment]
Thank you! I can also confirm everything seems to be working perfect now with DecSync and Syncthing on Android to --> Syncthing, Radicale with this plug-in, and Thunderbird on Windows. I am super happy with this setup :)

**Comment by therealjeybe** [comment]
Awesome, seems to work now! Thanks for your efforts with all the DecSync stuff!
